# Generated by Django 5.2.17 on 2026-08-14 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date this gratitude entry belongs to.')),
                ('content', models.TextField(help_text='The gratitude reflection text (typically up to 1000 characters).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entry was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entry was last updated.')),
                ('owner', models.ForeignKey(help_text='The user who created this journal entry.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='unique_user_daily_entry')],
            },
        ),
    ]
