# Generated by Django 5.2.17 on 2026-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title or theme of the gratitude reflection.', max_length=200),
        ),
    ]
